name = "ChemicalEquilibrium"
uuid = "c73daa1d-2164-49f1-bdc3-1ba142d7b6fc"
authors = ["Maltsev Maxim <daerus21@yandex.ru>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
